# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: ruby:2.3

cache:
  paths:
  - vendor

test:
  script:
  - echo "Hi"
  except:
    - master

pages:
  script:
  - git config --global user.email "orta+dangersystems@artsy.net"
  - git config --global user.name "Danger.Systems"
  - apt-get update -yqqq
  - apt-get install -y nodejs
  - bundle install --path vendor
  - bundle exec rake generate
  - bundle install --path vendor
  - cd static
  - bundle exec middleman build
  artifacts:
    paths:
    - static/build
  only:
  - master
