language: ruby
# branches:
#   only:
#   - master
rvm:
- 2.1.3

install:
  - git config --global user.email "orta+dangersystems@artsy.net"
  - git config --global user.name "Danger.Systems"
  - cd static
  - gem install bundler
  - bundle install

script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/danger/danger.systems.git"
  - bundle exec rake generate
  - cd static
  - bundle install
  - bundle exec rake deploy
