language: ruby
branches:
  only:
  - master
rvm:
- 2.1.3

install:
  - git config --global user.email "bots@cocoapods.org"
  - git config --global user.name "CocoaPods Bot"
  - cd static
  - gem install bundler
  - bundle install

script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/danger/danger.systems.git"
  - cd ..
  - rake deploy
